### ISSUE TITLE
Email address in README

### ISSUE THREAD

**Issue by celtic-coder** [johnchandlerburnham/agathic.com#1]
Hi John (@johnchandlerburnham),

Your email address `john@agathic.com` is displayed in the [README](https://github.com/johnchandlerburnham/agathic.com/blob/main/README.md#community-guidelines) markdown file in the **Community Guidelines** section. 

However, your **Contact Information** in your [Home.md](https://github.com/johnchandlerburnham/agathic.com/blob/main/Home.md) page uses the form `<my-first-name>@<this-domain>` as you make it clear that you do not want your email address to be harvested.

If your email address is required in this kind of README, perhaps you could disguise it in some way? Maybe you could use a plain text link -- something like john-AT-agathic.com for example? 

On your website, the link appears with the "mailto:" prefix. Such a link, as your rightly noted, is fodder for harvesters.

![mailto-link](https://user-images.githubusercontent.com/11787866/168487996-82835142-3e35-4c77-a6df-5ba7ba0ab228.png)

Does __Obsidian Publish__ automatically add the "mailto" to the HTML for such a link?

![obsidian-publish-mailto](https://user-images.githubusercontent.com/11787866/168488393-5cbe1415-0009-40ab-b20f-81a38907390b.png)

In any case, it might be wise to adjust your email address in your README file.

Kind Regards,
Liam

**Comment by johnchandlerburnham** [comment]
Yeah, I guess there's not really a lot of point in trying to obfuscate this address when it's listed on my Github profile too. I've made the address in Home.md explicit and removed the mailto in README.md.

Thanks for catching this!
